#!/usr/bin/env python3
# 
# many thanks to Mikhail Korobov - http://nbviewer.ipython.org/github/tpeng/python-crfsuite/blob/master/examples/CoNLL%202002.ipynb#

from optparse import OptionParser

parser = OptionParser()
parser.add_option("-f", "--file", dest="infile",
                  help="read conll data from this file")
parser.add_option("-x", "--extractor", dest="extractor_module",
                  help="name of feature extractor python module", default="base_extractors")
parser.add_option("-o", "--output", dest="outfile",
                  help="specify destination CRFsuite model file (optional, filename autogenerated if not specified)", default="")
parser.add_option("-c", "--clusters", dest="clusterfile",
                  help="path to brown clusters file")
parser.add_option("-i", "--max-iter", dest="max_iterations",
                  help="number of training iterations", default=50)
parser.add_option("-m", "--min-freq", dest="min_freq",
                  help="minimum number of feature occurrences for inclusion", default=2)
parser.add_option("-v", "--verbose-training", dest="trainer_verbose", action="store_true",
                  help="output crfsuite progress during model training", default=False)

(options, args) = parser.parse_args()
if not options.infile:
	parser.error('please specify at least an input file')

import sys
print('init', file=sys.stderr)

import nltk
import pycrfsuite
import time

# local imports
import er

# import feature extraction
extractors = __import__(options.extractor_module)
word2features = extractors.word2features
featurise = extractors.featurise

if options.clusterfile:
	print('reading in brown clusters', file=sys.stderr)
	brown_cluster = er.load_brown_clusters(options.clusterfile)
else:
	brown_cluster = {}

print('reading source data', file=sys.stderr)
y_train, X_train = er.load_conll_file(options.infile)

trainer = pycrfsuite.Trainer(verbose=options.trainer_verbose)

print('building feature representations for examples', file=sys.stderr)

i = 0
for xseq,yseq in zip(X_train, y_train):
	xrepr = featurise(xseq, brown_cluster)
	trainer.append(xrepr, yseq)

	i += 1
	if not i % 100:
		print('.', end='', file=sys.stderr)
		if not i % 1000:
			print(i, end='', file=sys.stderr)
		sys.stderr.flush()
print(i, file=sys.stderr)

trainer.set_params({
    'c1': 1.0,   # coefficient for L1 penalty
    'c2': 1e-3,  # coefficient for L2 penalty
    'feature.minfreq': options.min_freq,
    'max_iterations': options.max_iterations,  # stop earlier
    'feature.possible_transitions': True,	# include transitions that are possible, but not observed
    'feature.possible_states': True,			# include states that are possible, but not observed
#    'source_clusters': options.clusterfile,
#    'source_input': options.infile,
#    'source_built': time.strftime('%c'),
})


print('CRF parameters:', trainer.get_params(), file=sys.stderr)

if not options.outfile:
	options.outfile = options.infile.split('/')[-1] + time.strftime('.%Y%m%d-%H%M%S') + '.crfsuite.model'
trainer.train(options.outfile)

print('model written to ' + options.outfile, file=sys.stderr)